include:
  - dighosp-docs/compose.yml
  - dighosp-des/compose.yml
  - dighosp-frontend/compose.yml
  - nginx/compose.yml

services:
  # Local database for the BIM module.
  mongo:
    image: mongo:jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-pw
    volumes:
      - dev-mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand(\"ping\").ok' --quiet"]
      interval: 10s
      timeout: 3s
      retries: 5
    secrets:
      - mongo-root-pw
  # Admin portal for the local database.
  mongo-express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_SITE_BASEURL: /mongoadmin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo-root-pw

      ME_CONFIG_MONGODB_ENABLE_ADMIN : true
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo-pw
    ports:
      - "127.0.0.1:8081:8081"
    secrets:
      - mongo-root-pw
      - mongo-pw
  # A separate database for managing worker tasks -- used by the 'rq' Python package.
  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
volumes:
  dev-mongo:
secrets:
  mongo-root-pw:
    file: ./secrets/mongo-root-pw.txt
  mongo-pw:
    file: ./secrets/mongo-pw.txt