services:
  # FastAPI
  des-api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      MONGO_URL: mongo
      MONGO_PORT: 27017
      MONGO_PASSWORD_FILE: /run/secrets/mongo-root-pw
      REDIS_URL: redis
      REDIS_PORT: 6379
      FASTAPI_ROOT: ""
    volumes:
      - "./dighosp_des:/app/dighosp_des:rw"
    ports:
      - "8000:8000"
    secrets:
      - mongo-root-pw
    stop_grace_period: 3s
  # A worker for handling long-running BIM module tasks. Runs tasks sequentially from a queue.
  redis-worker:
    scale: 8
    build:
      context: .
      dockerfile: redis-worker.Dockerfile
    depends_on:
      - redis
    environment:
      MONGO_URL: mongo
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASSWORD_FILE: /run/secrets/mongo-root-pw
      REDIS_URL: redis
      REDIS_PORT: 6379
    secrets:
      - mongo-root-pw
    stop_grace_period: 3s
volumes:
  dev-mongo:
