services:
  frontend:
    build:
      context: .
      additional_contexts:
        assets: ../assets
      dockerfile: Dockerfile
    environment:
      TIMEOUT: 120
      WORKERS: 4
      ASSETS_DIRNAME: "/app/assets"
      DES_FASTAPI_URL: "http://webproxy/api/des"
    ports:
      - "8000:8000"
    stop_grace_period: 3s
